spring.application.name=App
# ==========================================
# CONFIGURACION DE LA BASE DE DATOS LOCAL (H2)
# ==========================================

# Le dice a H2 que guarde la base de datos en un archivo dentro de la carpeta "db_local"
spring.datasource.url=jdbc:h2:file:./db_local/remates_db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==========================================
# CONFIGURACION DE HIBERNATE (JPA)
# ==========================================

# El dialecto para que Spring hable correctamente con H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# MAGIA: "update" hace que Spring cree las tablas de los objetos si no existen,
# y que actualice las columnas si le agregas campos nuevos, SIN borrar tus datos!
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de Java las consultas SQL que hace por detras (muy util para ver errores)
spring.jpa.show-sql=true

# ==========================================
# CONSOLA H2 (Opcional, para ver tus tablas)
# ==========================================
# Te permite entrar a http://localhost:8080/h2-console para ver tu base de datos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Desactiva la redirección a páginas de error personalizadas
spring.web.error.include-message=always
spring.web.error.include-stacktrace=always
spring.web.error.include-binding-errors=always